### ISSUE TITLE
对前台菜单进行权限控制

### ISSUE THREAD

**Issue by jliuold** [skill6/skill6-website-backend#75]
![image](https://user-images.githubusercontent.com/14869749/45953041-70085d80-c03b-11e8-9486-a44b4851a566.png)
如上图，目前想将菜单做成动态的，初期隐藏部分菜单，仅上线文件共享等功能，所以需要后台的支撑

**Comment by CrazyHusen** [comment]
可做，概念方案如下：
1、shiro细分权限，对用户显示的菜单通过管理端配置，存储在数据库中；
2、用户访问时从数据库读取显示的菜单；
3、用户可访问的菜单通过用户是否登录和登录用户的权限获取；
4、后期可实现对部分用户内测新功能；
